version: "3"
services:
  flask:
    build:
      context: .
      network: host
    restart: always
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "5100"
    depends_on:
      - rabbit
    entrypoint: gunicorn
    command: app:app -w 5 -b 0.0.0.0:5100 # worker number (2 x cores on prod machine) + 1
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
    ports:
      - "8080:8080"
  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  celery:
    build:
      context: .
      network: host
    volumes:
      - type: bind
        source: .
        target: /app
    entrypoint: celery
    command: -A workerA worker -n worker@%h --loglevel=info
    links:
      - rabbit
    depends_on:
      - rabbit
